export const WALLET_ERROR_CODES = [
  'invalid_credential',
  'entropy_unavailable',
  'invalid_supplemental_entropy',
  'invalid_address',
  'invalid_transaction',
  'explorer_unavailable',
  'invalid_amount',
  'invalid_coin',
  'coin_unavailable',
  'insufficient_funds',
  'fee_rate_too_low',
  'transaction_confirmed',
  'transaction_not_replaceable',
  'acceleration_unavailable',
  'address_not_discardable',
  'address_not_found',
  'address_context_changed',
  'network_unavailable',
  'node_syncing',
  'node_history_unavailable',
  'node_admission_required',
  'fee_estimate_unavailable',
  'wallet_locked',
  'invalid_inactivity_timeout',
  'wallet_not_found',
  'wallet_selection_changed',
  'history_changed',
  'wallet_policy_changed',
  'invalid_mnemonic',
  'invalid_label',
  'label_export_invalid',
  'label_import_invalid',
  'label_import_conflict',
  'wallet_already_exists',
  'wallet_corrupt',
  'secure_storage_unavailable',
  'onboarding_cancelled',
  'onboarding_expired',
  'wrong_wallet_kind',
  'proposal_not_found',
  'broadcast_failed',
  'invalid_wallet_name',
  'invalid_cosigner_count',
  'unsafe_threshold',
  'duplicate_fingerprint',
  'duplicate_xpub',
  'invalid_descriptor',
  'invalid_signer_import',
  'import_too_large',
  'private_material_rejected',
  'invalid_fingerprint',
  'invalid_derivation_path',
  'wrong_network',
  'network_switch_unavailable',
  'invalid_network',
  'unsafe_network_selection',
  'network_selection_failed',
  'unsafe_test_root',
  'invalid_node_config',
  'invalid_scan_settings',
  'invalid_payment_request',
  'hardware_unavailable',
  'hardware_pairing_required',
  'hardware_policy_unsupported',
  'hardware_policy_name_conflict',
  'hardware_verification_invalid',
  'hardware_not_approved',
  'hardware_timeout',
  'hardware_busy',
  'hardware_cancelled',
  'hardware_response_too_large',
  'hardware_wrong_network',
  'invalid_hardware_response',
  'hardware_command_failed',
  'hardware_io_error',
  'hardware_ambiguous',
  'hardware_address_mismatch',
  'invalid_hardware_request',
  'hardware_pin_rejected',
  'hardware_challenge_expired',
  'hardware_scan_expired',
  'hardware_scan_superseded',
  'hardware_wallet_selection_required',
  'malformed_psbt',
  'psbt_too_large',
  'proposal_mismatch',
  'invalid_signature',
  'address_gap_limit_reached',
  'scan_in_progress',
  'scan_not_running',
  'scan_cancelled',
  'scan_interrupted',
  'initial_scan_required',
  'sync_in_progress',
  'sync_cancelled',
  'unknown_signer',
  'no_new_signatures',
  'no_inputs',
  'psbt_merge_failed',
  'signature_not_found',
  'hardware_signature_missing',
  'unsupported_sighash',
  'premature_finalization',
  'insufficient_signatures',
  'finalization_failed',
  'rate_limited',
  'invalid_backup',
  'invalid_ur',
  'backup_too_large',
  'backup_mismatch',
  'backup_export_failed',
  'file_reveal_unavailable',
  'confirmation_mismatch',
  'invalid_timeline',
  'invalid_decay',
  'invalid_expansion',
  'invalid_signer_count',
  'duplicate_signer',
  'recovery_signer_reused',
  'unknown_spending_path',
  'immature_spending_path',
  'invalid_delay',
  'invalid_key',
  'policy_too_complex',
  'policy_compilation_failed',
  'unsupported_wallet_policy',
  'mainnet_disabled',
  'diagnostics_unavailable',
  'internal_error'
] as const;

export type WalletErrorCode = (typeof WALLET_ERROR_CODES)[number];

export type WalletErrorDetails = {
  requestedBirthdayBlock?: number;
  requiredBlock?: number;
  earliestRetainedBlock?: number;
  minimumBirthdayBlock?: number;
};

const walletErrorCodes = new Set<string>(WALLET_ERROR_CODES);

export function walletErrorCode(value: unknown): WalletErrorCode {
  return typeof value === 'string' && walletErrorCodes.has(value)
    ? (value as WalletErrorCode)
    : 'internal_error';
}

export class WalletError extends Error {
  constructor(
    public readonly code: WalletErrorCode,
    message: string,
    public readonly existingWalletId: string | null = null,
    public readonly details: WalletErrorDetails | null = null
  ) {
    super(message);
    this.name = 'WalletError';
  }
}
