<script lang="ts">
  import { Check, Copy, Cpu, Download, FileUp, LockKeyhole, X } from '@lucide/svelte';
  import { onMount } from 'svelte';
  import Button from '$lib/components/Button.svelte';
  import Modal from '$lib/components/Modal.svelte';
  import PasswordField from '$lib/components/PasswordField.svelte';
  import { copyText } from '$lib/clipboard';
  import { shortSats } from '$lib/data';
  import { toast } from '$lib/stores/toasts';
  import { downloadText, readTransferFile } from '$lib/transfer';
  import { feeRate, sats, walletService, type FeeEstimates, type HardwareDevice, type MultisigProposal, type MultisigWallet } from '$lib/wallet';
  import { defaultConfig, networkName } from '$lib/config';
  import { addressPrefixForNetwork, hasAddressPrefixForNetwork } from '$lib/wallet/policy';
  let wallet = $state<MultisigWallet|null>(null), proposal=$state<MultisigProposal|null>(null), estimates=$state<FeeEstimates|null>(null);
  let address=$state(''), amount=$state(''), selectedRate=$state(2), pin=$state(''), imported=$state(''), txid=$state(''), error=$state('');
  let busy=$state(false), deviceOpen=$state(false), importOpen=$state(false), devices=$state<HardwareDevice[]>([]);
  const amountSats=$derived(Math.round(Number(amount||0))), addressValid=$derived(hasAddressPrefixForNetwork(address,defaultConfig.network)), valid=$derived(addressValid&&amountSats>0&&selectedRate>0);
  onMount(async()=>{try{wallet=await walletService.multisigWallet();estimates=await walletService.estimateFees();selectedRate=Number(estimates.standard);proposal=(await walletService.multisigProposals())[0]??null;}catch(cause){error=cause instanceof Error?cause.message:'Could not load vault.';}});
  async function prepare(){if(!valid)return;busy=true;error='';try{proposal=await walletService.prepareMultisigPayment(address,sats(amountSats),feeRate(selectedRate));}catch(cause){error=cause instanceof Error?cause.message:'Could not prepare payment.';}finally{busy=false;}}
  async function scan(){deviceOpen=true;busy=true;error='';try{devices=await walletService.listHardwareDevices();}catch(cause){devices=[];error=cause instanceof Error?cause.message:'Could not find hardware.';}finally{busy=false;}}
  async function sign(device:HardwareDevice){if(!proposal)return;busy=true;try{proposal=await walletService.signMultisigWithHardware(proposal.proposalId,device.id);deviceOpen=false;toast({title:'Signature added',description:`${proposal.signed} of ${proposal.required} signatures`,tone:'success'});}catch(cause){error=cause instanceof Error?cause.message:'Device signing failed.';}finally{busy=false;}}
  async function importPsbt(){if(!proposal||!imported.trim())return;busy=true;try{proposal=await walletService.importMultisigProposal(proposal.proposalId,imported);imported='';importOpen=false;toast({title:'Signed PSBT merged',description:`${proposal.signed} of ${proposal.required} signatures`,tone:'success'});}catch(cause){error=cause instanceof Error?cause.message:'PSBT import failed.';}finally{busy=false;}}
  async function broadcast(){if(!proposal||!pin)return;busy=true;error='';try{const result=await walletService.broadcastMultisigProposal(proposal.proposalId,pin);txid=result.txid;pin='';toast({title:'Vault transaction broadcast',description:`Balance ${shortSats(result.snapshot.balance.total)} sats`,tone:'success'});}catch(cause){error=cause instanceof Error?cause.message:'Broadcast failed.';pin='';}finally{busy=false;}}
  async function cancel(){if(!proposal)return;await walletService.cancelMultisigProposal(proposal.proposalId);proposal=null;address='';amount='';}
  async function copyPsbt(){if(!proposal)return;await copyText(proposal.psbt);toast({title:'PSBT copied',tone:'success'});}
  async function loadPsbtFile(event:Event){const input=event.currentTarget as HTMLInputElement;const file=input.files?.[0];input.value='';if(!file)return;try{imported=await readTransferFile(file);toast({title:'Signed PSBT file loaded',tone:'success'});}catch(cause){error=cause instanceof Error?cause.message:'Could not read PSBT file.';}}
</script>

<div class="page narrow-page send-page"><header class="page-header"><div><p class="eyebrow">MULTISIG SEND</p><h1>Send from vault</h1><p class="subtitle">Prepare once, then collect signatures in any order.</p></div><Button variant="secondary" href="/multisig">Back to vault</Button></header>
{#if txid}<section class="empty-state success-state"><span class="empty-icon success"><Check size={25}/></span><h2>Transaction broadcast</h2><p>The signed transaction was accepted by regtest.</p><div class="txid-box"><span>Transaction ID</span><code>{txid}</code></div><Button href="/multisig">Return to vault</Button></section>
{:else if !proposal}<form class="form-card" onsubmit={(e)=>{e.preventDefault();prepare();}}><label class="field"><span>Bitcoin address</span><input aria-label="Bitcoin address" bind:value={address} placeholder="{addressPrefixForNetwork(defaultConfig.network)}q…"/>{#if address&&!addressValid}<em>Enter a valid {networkName(defaultConfig.network)} address</em>{/if}</label><label class="field"><span>Amount</span><div class="amount-input"><input aria-label="Amount" bind:value={amount} inputmode="numeric" placeholder="0"/><b>sats</b></div></label><label class="field"><span>Fee rate</span><div class="amount-input"><input aria-label="Fee rate" bind:value={selectedRate} inputmode="decimal"/><b>sat/vB</b></div><small>{estimates?.source??'Loading fee estimates…'}</small></label>{#if error}<p class="form-error">{error}</p>{/if}<Button type="submit" size="large" class="full" disabled={!valid||busy}>{busy?'Preparing…':'Review multisig payment'}</Button></form>
{:else}<section class="form-card"><div class="review-amount"><span>You send</span><strong>{shortSats(Number(proposal.amount))} <small>sats</small></strong></div><dl class="details-list"><div><dt>To</dt><dd class="mono">{proposal.recipient}</dd></div><div><dt>Network fee</dt><dd>{shortSats(Number(proposal.fee))} sats</dd></div><div><dt>Fee rate</dt><dd>{proposal.feeRate} sat/vB</dd></div><div class="total"><dt>Total</dt><dd>{shortSats(Number(proposal.total))} sats</dd></div></dl>
<div class="signature-heading"><div><h2>Signatures</h2><p>{proposal.signed} of {proposal.required} collected</p></div><span class="policy-pill">{proposal.signed} of {proposal.required}</span></div><div class="signer-progress">{#each wallet?.cosigners??[] as signer}<div class:signed={proposal.signedFingerprints.includes(signer.fingerprint)}>{#if proposal.signedFingerprints.includes(signer.fingerprint)}<Check size={15}/>{:else}<span></span>{/if}<strong>{signer.label}</strong><small>{signer.fingerprint}</small></div>{/each}</div>
<div class="psbt-actions"><Button variant="secondary" onclick={scan}><Cpu size={16}/>Sign with device</Button><Button variant="secondary" onclick={()=>importOpen=true}><FileUp size={16}/>Import signed PSBT</Button><Button variant="secondary" onclick={copyPsbt}><Copy size={16}/>Copy PSBT</Button><Button variant="secondary" onclick={()=>proposal&&downloadText(`satchel-${proposal.proposalId}.psbt`,proposal.psbt)}><Download size={16}/>Save PSBT</Button></div>
{#if proposal.canFinalize}<div class="ready-panel"><LockKeyhole size={18}/><div><strong>Ready to finalize</strong><small>Enter the coordinator app PIN. Hardware signatures are already inside the PSBT.</small></div></div><PasswordField label="App PIN" inputLabel="App PIN" bind:value={pin} autocomplete="current-password"/><Button size="large" class="full" disabled={!pin||busy} onclick={broadcast}>{busy?'Finalizing…':'Finalize & broadcast'}</Button>{/if}{#if error}<p class="form-error">{error}</p>{/if}<Button variant="ghost-danger" class="full" onclick={cancel}><X size={15}/>Cancel proposal</Button></section>{/if}</div>

<Modal open={deviceOpen} title="Sign with hardware" description="Verify recipient, amount, fee, and wallet policy on the device." onclose={()=>deviceOpen=false}>{#if busy}<div class="device-scan"><Cpu size={20}/><span>Looking for devices…</span></div>{:else if devices.length===0}<div class="device-scan"><strong>No device found</strong><span>Connect an HWI-compatible device, or use signed PSBT import.</span><Button variant="secondary" onclick={scan}>Scan again</Button></div>{:else}<div class="source-list">{#each devices as device}<button onclick={()=>sign(device)}><Cpu size={18}/><span><strong>{device.label}</strong><small>{device.fingerprint??'Fingerprint unavailable'}</small></span></button>{/each}</div>{/if}</Modal>
<Modal open={importOpen} title="Import signed PSBT" description="Only signatures for this exact proposal are accepted." onclose={()=>importOpen=false}><label class="file-action"><FileUp size={16}/>Choose PSBT file<input aria-label="Choose signed PSBT file" type="file" accept=".psbt,text/plain" onchange={loadPsbtFile}/></label><label class="field"><span>Signed PSBT</span><textarea aria-label="Signed PSBT" rows="6" bind:value={imported} placeholder="cHNidP8…"></textarea></label><div class="modal-footer"><Button variant="secondary" onclick={()=>importOpen=false}>Cancel</Button><Button disabled={!imported.trim()||busy} onclick={importPsbt}>Validate & merge</Button></div></Modal>
