limit_req_zone $binary_remote_addr zone=groot_gateway_ip:10m rate=25r/s;
limit_conn_zone $binary_remote_addr zone=groot_gateway_conn:10m;
limit_req_zone $binary_remote_addr zone=groot_gateway_enroll:10m rate=1r/m;
