<script lang="ts">
  import { Check, FileUp } from '@lucide/svelte';
  import { goto } from '$app/navigation';
  import { onDestroy } from 'svelte';
  import Button from '$lib/components/Button.svelte';
  import FieldCounter from '$lib/components/FieldCounter.svelte';
  import PasswordField from '$lib/components/PasswordField.svelte';
  import { toast } from '$lib/stores/toasts';
  import { walletService, type RecoveryDrill } from '$lib/wallet';
  let backup=$state(''),walletName=$state('Recovered wallet'),pin=$state(''),confirmation=$state(''),drill=$state<RecoveryDrill|null>(null),verified=$state(false),busy=$state(false),error=$state('');
  async function inspect(){busy=true;error='';drill=null;verified=false;try{drill=backup.trimStart().startsWith('BSMS 1.0')?await walletService.inspectMultisigBsms(backup):await walletService.recoveryDrill(backup);}catch(cause){error=cause instanceof Error?cause.message:'Invalid backup.';}finally{busy=false;}}
  onDestroy(()=>{pin='';confirmation='';});
  async function recover(){if(!drill||!verified||pin!==confirmation)return;busy=true;error='';try{if(backup.trimStart().startsWith('BSMS 1.0'))await walletService.recoverMultisigBsms(walletName,backup,pin);else await walletService.recoverMultisig(backup,pin);toast({title:'Wallet recovered',description:'Descriptors were restored. Run a full rescan before relying on the balance.',tone:'success'});await goto('/multisig');}catch(cause){error=cause instanceof Error?cause.message:'Recovery failed.';}finally{pin='';confirmation='';busy=false;}}
</script>
<div class="page narrow-page"><header class="page-header"><div><p class="eyebrow">DESCRIPTOR RECOVERY</p><h1>Recover multisig wallet</h1><p class="subtitle">Validate a standard BSMS record or restore complete Groot recovery metadata.</p></div><Button variant="secondary" href="/settings">Cancel</Button></header>
<section class="form-card"><label class="field"><span>Descriptor backup</span><textarea aria-label="Recovery descriptor backup" rows="10" bind:value={backup} placeholder="Paste BSMS 1.0 or Groot JSON"></textarea></label><Button variant="secondary" class="full" disabled={!backup.trim()} loading={busy} loadingLabel="Validating backup…" onclick={inspect}><FileUp size={15}/>Validate backup</Button>
{#if drill}<div class="drill-result passed"><Check size={17}/><span><strong>Backup is valid</strong><small>Verify this first receive address against your offline record.</small><code>{drill.firstAddress}</code></span></div><label class="check-row"><input aria-label="I verified the first receive address" type="checkbox" bind:checked={verified}/><span><strong>I verified the first receive address</strong><small>A mismatch means this is not the wallet you intended to recover.</small></span></label>{#if backup.trimStart().startsWith('BSMS 1.0')}<label class="field"><span>Wallet name</span><input aria-label="Recovered wallet name" bind:value={walletName} maxlength="48"/><FieldCounter value={walletName} max={48}/></label><p class="field-hint">BSMS does not include private labels. Signers will be named Signer 1, Signer 2, and so on.</p>{/if}<div class="credential-grid"><PasswordField label="New app PIN" inputLabel="New wallet app PIN" bind:value={pin} autocomplete="new-password"/><PasswordField label="Confirm app PIN" inputLabel="Confirm new wallet app PIN" bind:value={confirmation} autocomplete="new-password"/></div>{#if pin&&confirmation&&pin!==confirmation}<p class="form-error">PINs do not match.</p>{/if}<Button class="full" disabled={!verified||!walletName.trim()||!pin||pin!==confirmation} loading={busy} loadingLabel="Recovering wallet…" onclick={recover}>Recover wallet</Button>{/if}
{#if error}<p class="form-error" aria-live="polite">{error}</p>{/if}</section></div>
